#!/usr/bin/env python3
"""CDK app entry point. Generated by generate_templates.py.
  cdk deploy -c evidenceBucket=... (after `pip install aws-cdk-lib constructs`)
"""

from aws_cdk import App
from cdk_stack import EvidenceRulesStack

app = App()
EvidenceRulesStack(app, "FedrampSdrEvidenceRules")
app.synth()
