#!/usr/bin/env python3
"""Offline tests for the lock-aware SBOM builder. No network. Run:
    python validation/scripts/test_sbom.py

Covers both modes:
  - no committed requirements.lock  -> honest top-level pins, transitive=false
  - a committed requirements.lock   -> fully-resolved closure with SHA-256
                                       hashes, transitive=true
The lock case uses a synthetic lock written to a temp path so the test does not
depend on running pip-compile or on network access.
"""

import os
import sys
import json
import tempfile
import importlib.util

HERE = os.path.dirname(os.path.abspath(__file__))
SBOM_PY = os.path.join(HERE, "build_sbom.py")


def _load_module():
    spec = importlib.util.spec_from_file_location("build_sbom", SBOM_PY)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _scope(sbom):
    props = {p["name"]: p["value"] for p in sbom["metadata"].get("properties", [])}
    return props.get("sbom:scope"), props.get("sbom:transitive-included")


def main():
    passed = failed = 0

    def check(name, cond):
        nonlocal passed, failed
        if cond:
            passed += 1; print(f"  PASS {name}")
        else:
            failed += 1; print(f"  FAIL {name}")

    mod = _load_module()

    # Mode 1: no lock -> top-level pins, transitive not included.
    real_lock = mod.LOCK
    mod.LOCK = os.path.join(tempfile.gettempdir(), "no-such-lock-file.lock")
    try:
        comps = mod._parse_lock(mod.LOCK)
        check("no lock -> _parse_lock returns None", comps is None)
    finally:
        mod.LOCK = real_lock

    # Mode 2: a synthetic pip-compile-style lock -> resolved closure with hashes.
    lock_text = (
        "# generated by pip-compile\n"
        "jsonschema==4.26.0 \\\n"
        "    --hash=sha256:aaaa \\\n"
        "    --hash=sha256:bbbb\n"
        "attrs==25.4.0 \\\n"
        "    --hash=sha256:cccc\n"
        "    # via jsonschema\n"
    )
    with tempfile.TemporaryDirectory() as td:
        lp = os.path.join(td, "requirements.lock")
        open(lp, "w", encoding="utf-8").write(lock_text)
        parsed = mod._parse_lock(lp)
        check("lock parses every package (direct + transitive)",
              parsed is not None and set(parsed) == {"jsonschema", "attrs"})
        check("lock captures the version",
              parsed and parsed["jsonschema"][0] == "4.26.0")
        check("lock captures all hashes for a package",
              parsed and parsed["jsonschema"][1] == ["sha256:aaaa", "sha256:bbbb"])

    print(f"\n{passed}/{passed + failed} SBOM checks passed")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
